kind: ClusterSelector
apiVersion: configmanagement.gke.io/v1
metadata:
  name: cluster-env-dev
spec:
  selector:
    matchLabels:
      environment: dev
---
kind: ClusterSelector
apiVersion: configmanagement.gke.io/v1
metadata:
  name: cluster-env-prod
spec:
  selector:
    matchLabels:
      environment: prod
