apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
spec:
  template:
    spec:
      containers:
        - env:
            - name: ENV
              value: DEV
      - image: us-docker.pkg.dev/davec-op-project/gcr.io/app:0.1.3
